### ISSUE TITLE
Feature Request: API Access to Calculator

### ISSUE THREAD

**Issue by Programmer-Timmy** [IceMoonMagic/Satisfactory-Splitter-Calculator#10]
Hi! I really appreciate the calculator; it’s been incredibly helpful. I'd love to integrate it into my own project, and having an API would make that possible.

Are you considering adding an API to allow external projects to use the calculator programmatically?

My project is a tool designed to help users plan and manage their Satisfactory factories. It can automatically calculate production lines, and I would like to add a popup or similar feature for calculating splitters directly on the site.

**Comment by IceMoonMagic** [comment]
I would, but I don't think that's really possible with the current setup. 
As it's just hosted on GitHub pages, it doesn't have a back-end server to run an API and is technically a static site. All the work is done in the browser.

I could probably make something that reads and runs from the anchor and / or query string of the URL, but I don't know of a way to return / respond that value back (besides just displaying the whole page in a iframe or something...).

A few things you could do:
- Just import the relevant JS files from GitHub pages and run them yourself
  - It's compiled TS then bundled with Vite, so you'd have to read the `index.html` to get the `index-<chars>.js`, then use that to get the `splitRatio-<chars>.js` or `splitEven-<chars>.js` for the main runner functions, and finally figure out how to run it (using a worker and `onmessage` will probably still work)
- Use [Git Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and integrate / compile it with your project
  - I haven't really used submodules, so I don't know much about them
  - or alternatively, just copy the bits you want ([MIT License](https://github.com/IceMoonMagic/Satisfactory-Splitter-Calculator/blob/main/LICENSE))
    - you'd have to manually update if you wanted to but also protected from me accidentally breaking something...
- If you have somewhere to host it, there is technically the [python version](https://github.com/IceMoonMagic/Satisfactory-Splitter-Calculator/tree/main/python)
  - It hasn't really been touched since 8a2d2082 (besides moving it) and is missing a few features (though it does have the smart splitters that the ts one doesn't...)
  - It's also missing an HTTP API. `api.py` has what you need to call, but it needs something else to call it (e.g. Flask or AIOHTTP)

**Comment by Programmer-Timmy** [comment]
Yes, that's true; with GitHub Pages, it is not really possible. I self-host my site; I just grabbed an old PC and turned it into an Ubuntu server with [Virtualmin](https://www.virtualmin.com). Once set up, it's pretty easy.

Now that I am thinking about it, I could maybe add your page in an iframe. I will take a look later at how I can implement it. I still want to add a lot more features to my site and also drastically improve my own API.

Thanks for your fast reply!
