### ISSUE TITLE
Bottleneck problem with prime splitters

### ISSUE THREAD

**Issue by rala72** [IceMoonMagic/Satisfactory-Splitter-Calculator#6]
There is the problem with bottleneck if you use loopbacks in prime splitters as shown in the image in end of the following section [here](https://satisfactory.wiki.gg/wiki/Balancer#Load_balancer) _([this](https://satisfactory.wiki.gg/wiki/Tutorial:Prime_splitter_arrays) might also be relevant)_.

It would be awesome have two (or at least one) feature(s):

1. toggle for non-bottleneck option (if relevant for specific belts)
2. highlight in the result / graph, that there might be a bottleneck problem

**Comment by IceMoonMagic** [comment]
Huh, given how many times I've reworked this project, I'm surprised I've haven't come across (at at least, didn't pay attention to) the wiki's prime factor splitter stuff... I even reference the section it's in!

Anyway, both Graphviz and Mermaid support changing the styles of edges, so that should be fairly simple to implement. Though, I'll probably go for line thickness rather than color to avoid contrast and light vs dark issues.

A non-bottleneck option would be a tad trickier, as it would be reworking the solver a bit. Though, the loop back nodes / edges have been a cause sub optimal solutions (particularly with multiple inputs, which wasn't really specifically designed for). 
Things I could consider (congrats, this is a note now):
- completely rework the solver
  - seems unnecessary
  - tried using knapsack in the old python version, it was *way* slower (probably because the usage was used way too many times...)
  - though, the wiki's tutorial starts at the targets while this starts at the sources
- don't connect the loop back edges until the merging step
  - could be used to help with multi-input solutions
  - doesn't help Split Evenly
  - doesn't address bottlenecking
- instead of linking to the merger, find all (2 or 3) grandchildren of the merger, delete the merger (re-linking the input and output), and split / merge loop back belt into all grandchildren
  - sounds easier than trying to determine to do it during initial solving
  - have to make sure displayed numbers are still correct

I'll do some work on it and see how it goes.

**Comment by IceMoonMagic** [comment]
Is there ever a case such that after the first splitter on a source, subsequent sections have the possibility of bottlenecking (assuming the original source was workable)?

Like when splitting into 5, the bottleneck is by making it into 6. But for 10, it goes to 5 twice which goes to 6 twice which is less than 10 on either belt.

```mermaid
flowchart TD
	0[/5\]
	1[6]
	2{6}
	3{3}
	4[\1/]
	5[\1/]
	6{3}
	7[\1/]
	8[\1/]
	9[\1/]
	0 -- 5 --> 1
	1 == 6 ==> 2
	2 -- 3 --> 3
	2 -- 3 --> 6
	3 -- 1 --> 4
	3 -- 1 --> 5
	3 -- 1 --> 1
	6 -- 1 --> 7
	6 -- 1 --> 8
	6 -- 1 --> 9
```
```mermaid
flowchart TD
	10[/10\]
	11{10}
	12[6]
	13{6}
	14{3}
	15[\1/]
	16[\1/]
	17{3}
	18[\1/]
	19[\1/]
	20[\1/]
	21[6]
	22{6}
	23{3}
	24[\1/]
	25[\1/]
	26{3}
	27[\1/]
	28[\1/]
	29[\1/]
	10 -- 10 --> 11
	11 -- 5 --> 12
	11 -- 5 --> 21
	12 == 6 ==> 13
	13 -- 3 --> 14
	13 -- 3 --> 17
	14 -- 1 --> 15
	14 -- 1 --> 16
	14 -- 1 --> 12
	17 -- 1 --> 18
	17 -- 1 --> 19
	17 -- 1 --> 20
	21 == 6 ==> 22
	22 -- 3 --> 23
	22 -- 3 --> 26
	23 -- 1 --> 24
	23 -- 1 --> 25
	23 -- 1 --> 21
	26 -- 1 --> 27
	26 -- 1 --> 28
	26 -- 1 --> 29
```
Granted, it's not really something to worry about if given a set threshold nor will it likely change the complexity of implementing either way...

**Comment by rala72** [comment]
Honestly I prefer to make the most complex splitter (like 1→5) as soon as possible, to only have 1→2 remaining instead of having the 1→5 twice, so yes there is the possibility - especially if you use already the max of a belt as input.
